{
"amount" :111111,
"spanMonth":10,
"startDate":"2015-1-10",
"endDate":"2015-10-10",
"payCircle" : 3,
"payTotalCircle" : 10,
"interests" : 1,
"assureCost" : 1000.0,
"serviceCost" : 1000.0,
"overdueCostPercent" : 10,
"otherCost" : 1000.0,
"keepCost" : 1000.0,
"payWay" : "debx",
"firstPayDate" : "2015-4-10"   
}