#%RAML 0.8

title: Kunshan Dai
baseUri: http://kunshandai.avosapps.com/{version}
version: v1

/loan:
  /create_loan:
    post:
      queryParameters:
        amount:
          type: string
        spanMonth:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        payCircle:
          type: string
        payTotalCircle:
          type: string
        interests:
          type: string
        assureCost:
          type: string
        serviceCost:
          type: string
        overdueCostPercent:
          type: string
        otherCost:
          type: string
        keepCost:
          type: string
        payWay:
          type: string
        firstPayDate:
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "data": {
                    "id": "5529ec78e4b0da2c5e080694"
                  },
                  "code": 200
                }
  /create_contract:
    post:
      queryParameters:
        name:
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                }
  /generate_project:
    post:
      queryParameters:
        name:
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                }




