#%RAML 0.8

title: Kunshan Dai
baseUri: http://kunshandai.avosapps.com/{version}
version: v1
traits:
  - paged:
      queryParameters:
        pages:
          description: The number of pages to return
          type: number

/account:        
  /login:
    post:
      queryParameters:
        mobilePhoneNumber:
          description: |
            mobilePhoneNumber
          type: string
        password:
          description: |
            password
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                    "username": "18516171260",
                    "emailVerified": false,
                    "mobilePhoneNumber": "18516171260",
                    "mobilePhoneVerified": true,
                    "objectId": "551fea47e4b02dd0ab568b85",
                    "createdAt": "2015-04-04T13:42:31.367Z",
                    "updatedAt": "2015-04-04T13:42:59.487Z"
                }
        210:
          body:
            application/json:
              schema: |
                {
                  "code": 210,
                  "message": "The username and password mismatch."
                }
        211:
          body:
            application/json:
              schema: |
                {
                  "code": 211,
                  "message": "Could not find user"
                }
      description: login system with mobilePhoneNumber & password
  /logout:
    get:
      description: logout current user
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                    "username": "18516171260",
                    "emailVerified": false,
                    "mobilePhoneNumber": "18516171260",
                    "mobilePhoneVerified": true,
                    "objectId": "551fea47e4b02dd0ab568b85",
                    "createdAt": "2015-04-04T13:42:31.367Z",
                    "updatedAt": "2015-04-04T13:42:59.487Z"
                }
  /isLogin:
    get:
      description: check is current login or not
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                    "username": "18516171260",
                    "emailVerified": false,
                    "mobilePhoneNumber": "18516171260",
                    "mobilePhoneVerified": true,
                    "objectId": "551fea47e4b02dd0ab568b85",
                    "createdAt": "2015-04-04T13:42:31.367Z",
                    "updatedAt": "2015-04-04T13:42:59.487Z"
                }
        210:
          body:
            application/json:
              schema: |
                {
                  "result":false,
                  "code":210
                }
  /register:
    post:
      description: |
        Register a new user and verify mobilePhoneNumber (close verify in leancloud if necessary)
      queryParameters:
        mobilePhoneNumber:
          description: |
            mobilePhoneNumber
          type: string
        password:
          description: |
            password
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                    "username": "18516171260",
                    "emailVerified": false,
                    "mobilePhoneNumber": "18516171260",
                    "mobilePhoneVerified": true,
                    "objectId": "551fea47e4b02dd0ab568b85",
                    "createdAt": "2015-04-04T13:42:31.367Z",
                    "updatedAt": "2015-04-04T13:42:59.487Z"
                }
  /requestMobilePhoneVerif:
    get:
      description: |
        重新验证手机号
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "result":"success",
                  "code":200
                }
  /verifyUserMobilePhoneNumber:
    post:
      queryParameters:
        code:
          description: |
            code
          type: integer
      description: |
        验证手机号
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "result":"success",
                  "code":200
                }
  /requestEmailVerify:
    get:
      description: |
        发送验证邮件
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "result":"success",
                  "code":200
                }
  
/loan:
  /create_loan:
    post:
      description: |
        新建一个贷款项目
      queryParameters:
        amount:
          example: 10000.0
          type: string
        spanMonth:
          type: string
        startDate:
          description: 合同开始日期
          example: 2014-10-29
          type: date
        endDate:
          description: 合同结束日期
          example: 2014-10-29
          type: date
        payCircle:
          example: 2
          description: 每X月还一次款
          type: number
        payTotalCircle:
          example: 20
          description: 总共还款的月数
          type: number
        interests:
          description: 百分之N(按处理后的小数传递)
          example: 5
          type: number
        assureCost:
          example: 10000.0
          type: number
        serviceCost:
          type: number
        overdueCostPercent:
          description: 千分之N(按处理后的小数传递)
          example: 0.001
          type: number
        otherCost:
          type: number
        keepCost:
          type: number
        payWay:
          description: |
            还款方式,可能后期变动
          example: |
            {"debx":等额本息, "zqch":周期初还本付息,"zqmh":周期末还本付息,"qx":还全息}
          type: string
        firstPayDate:
          description: 首次还款时间
          type: date
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                    "data": {
                        "amount": 111111,
                        "spanMonth": 10,
                        "startDate": {
                            "__type": "Date",
                            "iso": "2015-01-09T16:00:00.000Z"
                        },
                        "endDate": {
                            "__type": "Date",
                            "iso": "2015-10-10T00:00:00.000Z"
                        },
                        "payCircle": 3,
                        "payTotalCircle": 10,
                        "interests": 0.01,
                        "overdueCostPercent": 0.01,
                        "otherCost": 1000,
                        "keepCost": 1000,
                        "payWay": "debx",
                        "firstPayDate": {
                            "__type": "Date",
                            "iso": "2015-04-09T16:00:00.000Z"
                        },
                        "objectId": "552a2736e4b0b40da36bd865",
                        "createdAt": "2015-04-12T08:05:10.090Z",
                        "updatedAt": "2015-04-12T08:05:10.090Z"
                    },
                    "code": 200
                }
  /generate_project:
    description: |
      未完成
    post:
      queryParameters:
        name:
          type: string
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                }

/contract:
  post:
    queryParameters:
      loander:
        description: |
          以json形式拼接用户信息
        type: string
        example: |
           {
             "name":"test",
             "mobilePhoneNumber":"18516171260",
             "certificateType":"shenfenzheng",
             "certificateNum":"542421421421321312312",
             "email":"yilaing@foxmail.com",
             "qq":"32727272992",
             "address":"fdsafasf",
             "wechat":"fasdfa",
             "attachments": ["552a0e61e4b0b40da36acc5b"]
           }
      assurer:
        description: |
          以json形式拼接用户信息
        type: string
        example: |
           {
             "name":"test",
             "mobilePhoneNumber":"18516171260",
             "certificateType":"shenfenzheng",
             "certificateNum":"542421421421321312312",
             "email":"yilaing@foxmail.com",
             "qq":"32727272992",
             "address":"fdsafasf",
             "wechat":"fasdfa",
             "attachments": ["552a0e61e4b0b40da36acc5b"]
           }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "data": {
                      "loanerId": "552a244ee4b0da2c5e0add15",
                      "assurerId": "552a244ee4b0da2c5e0add13"
                  },
                  "code": 200
              }
  /{id}:
    get:
      description: |
        未完成
      responses:
        200:
          body:
            application/json:
              example: |
               {
                
               }


/attachment:
  post:
    queryParameters:
      attachment:
        type: file
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "data": {
                      "metaData": {
                          "owner": "unknown",
                          "size": 527,
                          "mime_type": "text/plain"
                      },
                      "id": "552a2294e4b0b40da36ba7e7",
                      "url": "http://ac-gvw1ggob.clouddn.com/b7f1294b28cdbb96.md",
                      "name": "项目经理周总结模板.md"
                  },
                  "code": 200
              }
